name: cd

on:
  push:
    branches:
      - deployment

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Deploy Using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            cd ../www/wwwroot/abbs.puss.ink
            git pull origin deployment
            git status
            ../../../www/server/nodejs/v20.18.0/bin/npm install
            ../../../www/server/nodejs/v20.18.0/bin/npm build
            ../../../www/server/nodejs/v20.18.0/bin/pm2 reload abbs
            ../../../www/server/nodejs/v20.18.0/bin/pm2 restart abbs
